@startuml ACT_03_LIHAT_SURAT_KELUAR
!theme plain
!pragma useVerticalIf on
scale max 1600 width
skinparam wrapWidth 200

skinparam defaultFontSize 12\nskinparam TitleFontSize 14
skinparam swimlaneWidth 220
skinparam ActivityStartColor black
skinparam ActivityEndColor black
title ACT-03 - Lihat Surat Keluar / Asisten

|Admin / Asisten|
|System|

|Admin / Asisten|
start
:Buka menu Surat Keluar;

|System|
:Cek autentikasi & role;
:Ambil data surat keluar;
:Tampilkan daftar surat keluar;

|Admin / Asisten|
:Lihat daftar surat keluar;
:Klik surat ? lihat detail\n;

|System|
:Ambil data detail surat;
:Tampilkan halaman detail;

|Admin / Asisten|
:Lihat detail surat keluar;

stop
@enduml
