services:
    silab-app:
        container_name: silab-app
        image: silab
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8000:8000'
        volumes:
            - ./storage:/var/www/html/storage
            - ./.env:/var/www/html/.env
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - silab_network

networks:
    silab_network:
        driver: bridge
