version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 34.101.143.2
      DB_PORT: 3306
      DB_DATABASE: silab
      DB_USERNAME: silab
      DB_PASSWORD: Silabdsi2025!
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - ./.env:/var/www/html/.env
    networks:
      - silab_network

networks:
  silab_network:
    driver: bridge 