version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 34.101.143.2
      DB_PORT: 3306
      DB_DATABASE: silab
      DB_USERNAME: silab
      DB_PASSWORD: Silabdsi2025!
    volumes:
      - .:/var/www/html
    networks:
      - silab_network

networks:
  silab_network:
    driver: bridge 