
Enum "absensi_aslab_status_enum" {
  "hadir"
  "sakit"
  "izin"
  "alpa"
}

Enum "absensi_praktikan_status_enum" {
  "hadir"
  "sakit"
  "izin"
  "alpa"
}

Enum "detail_aset_status_enum" {
  "tersedia"
  "dipinjam"
}

Enum "detail_aset_keadaan_enum" {
  "baik"
  "rusak"
}

Enum "ganti_jadwal_piket_status_enum" {
  "pending"
  "approved"
  "rejected"
}

Enum "kegiatan_status_approval_enum" {
  "diajukan"
  "disetujui"
  "ditolak"
}

Enum "kegiatan_peserta_peran_enum" {
  "peserta"
  "panitia"
}

Enum "kelas_status_enum" {
  "aktif"
  "nonaktif"
}

Enum "kuesioner_tipe_enum" {
  "internal"
  "eksternal"
}

Enum "nominal_kas_periode_enum" {
  "mingguan"
  "bulanan"
}

Enum "pengumpulan_tugas_status_enum" {
  "dikumpulkan"
  "dinilai"
  "terlambat"
}

Enum "permohonan_aset_status_permohonan_enum" {
  "diajukan"
  "disetujui"
  "ditolak"
}

Enum "praktikan_praktikum_status_enum" {
  "aktif"
  "nonaktif"
}

Enum "profile_jenis_kelamin_enum" {
  "laki-laki"
  "perempuan"
}

Enum "proker_status_enum" {
  "belum_mulai"
  "sedang_berjalan"
  "selesai"
  "ditunda"
}

Enum "riwayat_keuangan_jenis_enum" {
  "masuk"
  "keluar"
}

Enum "riwayat_keuangan_jenis_pembayaran_kas_enum" {
  "normal"
  "lebih"
}

Enum "sertifikat_jenis_sertifikat_enum" {
  "asisten"
  "praktikan"
  "kepengurusan"
}

Enum "sertifikat_templates_kategori_enum" {
  "kegiatan"
  "praktikum"
  "aslab"
  "umum"
}

Enum "target_kuesioner_tipe_target_enum" {
  "role"
  "user"
  "lab"
}

Enum "tugas_praktikum_status_enum" {
  "aktif"
  "nonaktif"
}

Enum "wishlist_aset_urgensi_enum" {
  "rendah"
  "sedang"
  "tinggi"
  "sangat_tinggi"
}

Enum "wishlist_aset_status_item_enum" {
  "diajukan"
  "disetujui"
  "ditolak"
  "dipesan"
  "diterima"
}

Table "absensi" {
  "id" char(36) [pk, not null]
  "tanggal" date [not null]
  "jam_masuk" time [not null]
  "jam_keluar" time [default: NULL]
  "foto" varchar(255) [default: NULL]
  "jadwal_piket" char(36) [not null]
  "kegiatan" text [not null]
  "periode_piket_id" char(36) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "absensi_aslab" {
  "id" char(36) [pk, not null]
  "pertemuan_id" char(36) [not null]
  "user_id" char(36) [not null]
  "status" absensi_aslab_status_enum [not null, default: 'alpa']
  "waktu_absen" datetime [default: NULL]
  "keterangan" varchar(255) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "absensi_praktikan" {
  "id" char(36) [pk, not null]
  "pertemuan_id" char(36) [not null]
  "praktikan_id" char(36) [not null]
  "status" absensi_praktikan_status_enum [not null, default: 'alpa']
  "waktu_absen" datetime [default: NULL]
  "keterangan" varchar(255) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "aslab_praktikum" {
  "id" bigint(20) [pk, not null]
  "praktikum_id" varchar(255) [not null]
  "user_id" varchar(255) [not null]
  "catatan" text [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "cache" {
  "key" varchar(255) [pk, not null]
  "value" mediumtext [not null]
  "expiration" int(11) [not null]
}

Table "cache_locks" {
  "key" varchar(255) [pk, not null]
  "owner" varchar(255) [not null]
  "expiration" int(11) [not null]
}

Table "detail_aset" {
  "id" char(36) [pk, not null]
  "kategori_aset_id" char(36) [not null]
  "nama" varchar(255) [default: NULL]
  "kode_barang" varchar(255) [not null]
  "foto" varchar(255) [not null]
  "qr_code_path" varchar(255) [default: NULL]
  "status" detail_aset_status_enum [not null]
  "keadaan" detail_aset_keadaan_enum [not null]
  "jumlah" int(11) [not null, default: 1]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "dokumentasi_kegiatan" {
  "id" char(36) [pk, not null]
  "kegiatan_id" char(36) [not null]
  "judul" varchar(255) [not null]
  "file_path" varchar(255) [not null]
  "uploaded_by" char(36) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "failed_jobs" {
  "id" bigint(20) [pk, not null]
  "uuid" varchar(255) [not null]
  "connection" text [not null]
  "queue" text [not null]
  "payload" longtext [not null]
  "exception" longtext [not null]
  "failed_at" timestamp [not null, default: `current_timestamp()`]
}

Table "ganti_jadwal_piket" {
  "id" char(36) [pk, not null]
  "jadwal_piket_id" char(36) [not null]
  "periode_piket_id" char(36) [not null]
  "user_id" char(36) [not null]
  "hari_lama" varchar(255) [not null]
  "hari_baru" varchar(255) [not null]
  "alasan" text [not null]
  "status" ganti_jadwal_piket_status_enum [not null, default: 'pending']
  "approved_by" char(36) [default: NULL]
  "approved_at" timestamp [default: NULL]
  "catatan_admin" text [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "jadwal_piket" {
  "id" char(36) [pk, not null]
  "hari" varchar(255) [not null]
  "kepengurusan_lab_id" char(36) [not null]
  "user_id" char(36) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "jadwal_praktikum" {
  "id" char(36) [pk, not null]
  "kelas" varchar(255) [not null]
  "jam_mulai" time [not null]
  "jam_selesai" time [not null]
  "ruangan" varchar(255) [not null]
  "hari" varchar(255) [not null]
  "kelas_id" varchar(255) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "jawaban_kuesioner" {
  "id" char(36) [pk, not null]
  "respon_id" char(36) [not null]
  "pertanyaan_id" char(36) [not null]
  "jawaban" text [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "jobs" {
  "id" bigint(20) [pk, not null]
  "queue" varchar(255) [not null]
  "payload" longtext [not null]
  "attempts" tinyint(3) [not null]
  "reserved_at" int(10) [default: NULL]
  "available_at" int(10) [not null]
  "created_at" int(10) [not null]
}

Table "job_batches" {
  "id" varchar(255) [pk, not null]
  "name" varchar(255) [not null]
  "total_jobs" int(11) [not null]
  "pending_jobs" int(11) [not null]
  "failed_jobs" int(11) [not null]
  "failed_job_ids" longtext [not null]
  "options" mediumtext [default: NULL]
  "cancelled_at" int(11) [default: NULL]
  "created_at" int(11) [not null]
  "finished_at" int(11) [default: NULL]
}

Table "kategori_aset" {
  "id" char(36) [pk, not null]
  "nama" varchar(255) [not null]
  "deskripsi" text [not null]
  "laboratorium_id" char(36) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "kegiatan" {
  "id" char(36) [pk, not null]
  "proker_id" char(36) [not null]
  "nama_kegiatan" varchar(255) [not null]
  "deskripsi_kegiatan" text [default: NULL]
  "tipe_kegiatan" varchar(255) [default: NULL]
  "lokasi" varchar(255) [default: NULL]
  "link_meeting" varchar(255) [default: NULL]
  "tanggal_mulai" date [default: NULL]
  "tanggal_selesai" date [default: NULL]
  "status_approval" kegiatan_status_approval_enum [not null, default: 'diajukan']
  "approved_by" char(36) [default: NULL]
  "approved_at" timestamp [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "kegiatan_peserta" {
  "id" char(36) [pk, not null]
  "kegiatan_id" char(36) [not null]
  "user_id" char(36) [not null]
  "peran" kegiatan_peserta_peran_enum [not null, default: 'peserta']
  "is_lulus" tinyint(1) [not null, default: 0]
  "no_sertifikat" varchar(255) [default: NULL]
  "file_sertifikat" varchar(255) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "kelas" {
  "id" char(36) [pk, not null]
  "nama_kelas" varchar(255) [not null]
  "praktikum_id" varchar(255) [not null]
  "status" kelas_status_enum [not null, default: 'aktif']
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "kepengurusan_lab" {
  "id" char(36) [pk, not null]
  "tahun_kepengurusan_id" char(36) [not null]
  "laboratorium_id" char(36) [not null]
  "sk" varchar(255) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "kepengurusan_user" {
  "id" char(36) [pk, not null]
  "kepengurusan_lab_id" char(36) [not null]
  "user_id" char(36) [not null]
  "struktur_id" char(36) [not null]
  "is_active" tinyint(1) [not null, default: 1]
  "tanggal_bergabung" date [not null, default: '2025-08-16']
  "tanggal_keluar" date [default: NULL]
  "catatan" text [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "komponen_rubrik" {
  "id" char(36) [pk, not null]
  "tugas_praktikum_id" char(36) [not null]
  "nama_komponen" varchar(255) [not null]
  "deskripsi" text [default: NULL]
  "bobot" decimal(5,2) [not null]
  "nilai_maksimal" decimal(5,2) [not null, default: 100.00]
  "urutan" int(11) [not null, default: 1]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "kuesioner" {
  "id" char(36) [pk, not null]
  "judul" varchar(255) [not null]
  "deskripsi" text [default: NULL]
  "tipe" kuesioner_tipe_enum [not null]
  "link_eksternal" varchar(255) [default: NULL]
  "tanggal_mulai" datetime [default: NULL]
  "tanggal_selesai" datetime [default: NULL]
  "is_active" tinyint(1) [not null, default: 1]
  "is_mandatory" tinyint(1) [not null, default: 0]
  "dibuat_oleh" char(36) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "deleted_at" timestamp [default: NULL]
}

Table "laboratorium" {
  "id" char(36) [pk, not null]
  "nama" varchar(255) [not null]
  "logo" varchar(255) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "laporan_kegiatan" {
  "id" char(36) [pk, not null]
  "kegiatan_id" char(36) [not null]
  "jenis_laporan" varchar(255) [not null]
  "periode_bulan" int(11) [default: NULL]
  "periode_tahun" int(11) [default: NULL]
  "deskripsi_capaian" text [not null]
  "file_lpj" varchar(255) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "laporan_keuangan" {
  "id" char(36) [pk, not null]
  "bulan" varchar(255) [not null]
  "kepengurusan_lab_id" char(36) [not null]
  "pemasukan" int(11) [not null]
  "pengeluaran" int(11) [not null]
  "saldo_akhir" int(11) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "migrations" {
  "id" int(10) [pk, not null]
  "migration" varchar(255) [not null]
  "batch" int(11) [not null]
}

Table "model_has_permissions" {
  "permission_id" char(36) [not null]
  "model_type" varchar(255) [not null]
  "model_uuid" char(36) [not null]

  Indexes {
    (permission_id, model_uuid, model_type) [pk]
  }
}

Table "model_has_roles" {
  "role_id" char(36) [not null]
  "model_type" varchar(255) [not null]
  "model_uuid" char(36) [not null]

  Indexes {
    (role_id, model_uuid, model_type) [pk]
  }
}

Table "modul_praktikum" {
  "id" char(36) [pk, not null]
  "pertemuan_id" char(36) [default: NULL]
  "praktikum_id" char(36) [not null]
  "judul" varchar(255) [not null]
  "modul" varchar(255) [not null]
  "pertemuan" varchar(255) [not null]
  "is_public" tinyint(1) [not null, default: 0]
  "hash" varchar(255) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "nilai_rubrik" {
  "id" char(36) [pk, not null]
  "pengumpulan_tugas_id" char(36) [not null]
  "komponen_rubrik_id" varchar(255) [not null]
  "nilai" decimal(5,2) [not null]
  "catatan" text [default: NULL]
  "dinilai_oleh" varchar(255) [not null]
  "dinilai_at" timestamp [not null, default: `current_timestamp()`]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "nilai_tambahan" {
  "id" char(36) [pk, not null]
  "pengumpulan_tugas_id" char(36) [not null]
  "nilai" decimal(5,2) [not null]
  "kategori" varchar(255) [not null, default: 'bonus']
  "keterangan" text [default: NULL]
  "diberikan_oleh" varchar(255) [not null]
  "diberikan_at" timestamp [not null, default: `current_timestamp()`]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "nominal_kas" {
  "id" char(36) [pk, not null]
  "kepengurusan_lab_id" char(36) [not null]
  "nominal" decimal(10,2) [not null]
  "periode" nominal_kas_periode_enum [not null]
  "periode_mulai" date [default: NULL]
  "periode_berakhir" date [default: NULL]
  "is_active" tinyint(1) [not null, default: 1]
  "deskripsi" text [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "pengumpulan_tugas" {
  "id" char(36) [pk, not null]
  "tugas_praktikum_id" varchar(255) [not null]
  "praktikan_id" varchar(255) [not null]
  "file_pengumpulan" longtext [default: NULL]
  "catatan" text [default: NULL]
  "feedback" text [default: NULL]
  "nilai" decimal(5,2) [default: NULL]
  "status" pengumpulan_tugas_status_enum [not null, default: 'dikumpulkan']
  "submitted_at" timestamp [not null, default: `current_timestamp()`]
  "dinilai_at" timestamp [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "periode_piket" {
  "id" char(36) [pk, not null]
  "kepengurusan_lab_id" char(36) [not null]
  "nama" varchar(255) [not null]
  "tanggal_mulai" date [not null]
  "tanggal_selesai" date [not null]
  "isactive" tinyint(1) [not null, default: 0]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "permissions" {
  "id" char(36) [pk, not null]
  "name" varchar(255) [not null]
  "guard_name" varchar(255) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "permohonan_aset" {
  "id" char(36) [pk, not null]
  "user_pemohon_id" char(36) [not null]
  "laboratorium_id" char(36) [not null]
  "nomor_permohonan" varchar(100) [not null]
  "tanggal_permohonan" date [not null]
  "alasan_umum_pengadaan" text [not null]
  "status_permohonan" permohonan_aset_status_permohonan_enum [not null, default: 'diajukan']
  "catatan_approval" text [default: NULL]
  "approved_by" char(36) [default: NULL]
  "approved_at" timestamp [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "pertanyaan_kuesioner" {
  "id" char(36) [pk, not null]
  "kuesioner_id" char(36) [not null]
  "pertanyaan" text [not null]
  "tipe_pertanyaan" varchar(255) [not null]
  "opsi" json [not null]
  "wajib_diisi" tinyint(1) [not null, default: 0]
  "urutan" int(11) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "pertemuan_praktikum" {
  "id" char(36) [pk, not null]
  "praktikum_id" char(36) [not null]
  "kelas_id" char(36) [default: NULL]
  "judul" varchar(255) [not null]
  "deskripsi" text [default: NULL]
  "tanggal" datetime [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "praktikan" {
  "id" char(36) [pk, not null]
  "nim" varchar(255) [not null]
  "nama" varchar(255) [not null]
  "angkatan" varchar(255) [default: NULL]
  "no_hp" varchar(255) [default: NULL]
  "user_id" varchar(255) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "praktikan_praktikum" {
  "id" char(36) [pk, not null]
  "praktikan_id" char(36) [not null]
  "praktikum_id" char(36) [not null]
  "kelas_id" char(36) [not null]
  "status" praktikan_praktikum_status_enum [not null, default: 'aktif']
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "praktikum" {
  "id" char(36) [pk, not null]
  "mata_kuliah" varchar(255) [not null]
  "kepengurusan_lab_id" char(36) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "profile" {
  "id" char(36) [pk, not null]
  "nomor_induk" varchar(255) [not null]
  "jenis_kelamin" profile_jenis_kelamin_enum [not null]
  "foto_profile" varchar(255) [default: NULL]
  "alamat" varchar(255) [default: NULL]
  "no_hp" varchar(255) [default: NULL]
  "tempat_lahir" varchar(255) [default: NULL]
  "tanggal_lahir" date [default: NULL]
  "nomor_anggota" varchar(255) [default: NULL]
  "user_id" char(36) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "proker" {
  "id" char(36) [pk, not null]
  "struktur_id" char(36) [not null]
  "kepengurusan_lab_id" char(36) [not null]
  "nama_proker" varchar(255) [default: NULL]
  "tujuan" text [default: NULL]
  "sasaran" text [default: NULL]
  "output_kegiatan" text [default: NULL]
  "deskripsi" text [not null]
  "status" proker_status_enum [not null, default: 'belum_mulai']
  "status_pengajuan" varchar(255) [not null, default: 'draft']
  "tanggal_mulai" date [default: NULL]
  "tanggal_selesai" date [default: NULL]
  "keterangan" text [default: NULL]
  "kendala" text [default: NULL]
  "solusi" text [default: NULL]
  "saran" text [default: NULL]
  "file_proker" varchar(255) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "proker_dokumentasi" {
  "id" char(36) [pk, not null]
  "proker_id" char(36) [not null]
  "judul" varchar(255) [not null]
  "file_path" varchar(255) [not null]
  "uploaded_by" char(36) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "proker_parameter" {
  "id" char(36) [pk, not null]
  "proker_id" char(36) [not null]
  "nama_parameter" varchar(255) [not null]
  "bobot" smallint(5) [not null, default: 0]
  "capaian" smallint(5) [default: NULL]
  "urutan" smallint(5) [not null, default: 0]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "proker_pj" {
  "id" char(36) [pk, not null]
  "proker_id" char(36) [not null]
  "user_id" char(36) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "respon_kuesioner" {
  "id" char(36) [pk, not null]
  "kuesioner_id" char(36) [not null]
  "user_id" char(36) [not null]
  "tanggal_submit" datetime [not null, default: `current_timestamp()`]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "riwayat_keuangan" {
  "id" char(36) [pk, not null]
  "tanggal" date [not null]
  "nominal" int(11) [not null]
  "jenis" riwayat_keuangan_jenis_enum [not null]
  "deskripsi" varchar(255) [default: NULL]
  "bukti" varchar(255) [default: NULL]
  "user_id" char(36) [default: NULL]
  "kepengurusan_lab_id" char(36) [not null]
  "is_uang_kas" tinyint(1) [not null, default: 0]
  "jenis_pembayaran_kas" riwayat_keuangan_jenis_pembayaran_kas_enum [default: NULL]
  "catatan_pembayaran" text [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "roles" {
  "id" char(36) [pk, not null]
  "name" varchar(255) [not null]
  "guard_name" varchar(255) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "role_has_permissions" {
  "permission_id" char(36) [not null]
  "role_id" char(36) [not null]

  Indexes {
    (permission_id, role_id) [pk]
  }
}

Table "sertifikat" {
  "id" char(36) [pk, not null]
  "nomor_sertifikat" varchar(255) [not null]
  "jenis_sertifikat" sertifikat_jenis_sertifikat_enum [not null]
  "user_id" char(36) [not null]
  "kepengurusan_lab_id" char(36) [default: NULL]
  "praktikum_id" char(36) [default: NULL]
  "tanggal_terbit" date [not null]
  "file_path" varchar(255) [not null]
  "created_at" timestamp [not null, default: `current_timestamp()`]
}

Table "sertifikat_templates" {
  "id" char(36) [pk, not null]
  "nama" varchar(255) [not null]
  "file_path" varchar(255) [not null]
  "kategori" sertifikat_templates_kategori_enum [not null]
  "ref_id" char(36) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "sessions" {
  "id" varchar(255) [pk, not null]
  "user_id" char(36) [default: NULL]
  "ip_address" varchar(45) [default: NULL]
  "user_agent" text [default: NULL]
  "payload" longtext [not null]
  "last_activity" int(11) [not null]
}

Table "struktur" {
  "id" char(36) [pk, not null]
  "struktur" varchar(255) [not null]
  "jabatan_tunggal" tinyint(1) [not null, default: 1]
  "default_role_id" char(36) [default: NULL]
  "parent_id" char(36) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "struktur_permissions" {
  "id" bigint(20) [pk, not null]
  "jabatan" varchar(255) [not null]
  "permission" varchar(255) [not null]
  "description" text [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "surat" {
  "id" char(36) [pk, not null]
  "nomor_surat" varchar(255) [not null]
  "tanggal_surat" date [not null]
  "pengirim" char(36) [not null]
  "penerima" char(36) [not null]
  "perihal" varchar(255) [not null]
  "file" varchar(255) [default: NULL]
  "isread" tinyint(1) [not null, default: 0]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "tahun_kepengurusan" {
  "id" char(36) [pk, not null]
  "tahun" varchar(255) [not null]
  "isactive" tinyint(1) [not null, default: 0]
  "mulai" varchar(255) [not null]
  "selesai" varchar(255) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "target_kuesioner" {
  "id" char(36) [pk, not null]
  "kuesioner_id" char(36) [not null]
  "tipe_target" target_kuesioner_tipe_target_enum [not null]
  "nilai_target" varchar(255) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "tugas_praktikum" {
  "id" char(36) [pk, not null]
  "praktikum_id" varchar(255) [not null]
  "pertemuan_id" varchar(255) [default: NULL]
  "kelas_id" varchar(255) [default: NULL]
  "judul_tugas" varchar(255) [not null]
  "deskripsi" text [default: NULL]
  "file_tugas" varchar(255) [default: NULL]
  "deadline" datetime [default: NULL]
  "status" tugas_praktikum_status_enum [not null, default: 'aktif']
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "users" {
  "id" char(36) [pk, not null]
  "name" varchar(255) [not null]
  "email" varchar(255) [not null]
  "email_verified_at" timestamp [default: NULL]
  "password" varchar(255) [not null]
  "access_lab_id" char(36) [default: NULL]
  "remember_token" varchar(100) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "wishlist_aset" {
  "id" char(36) [pk, not null]
  "permohonan_aset_id" char(36) [not null]
  "nama_barang" varchar(255) [not null]
  "jenis_barang" varchar(100) [default: NULL]
  "spesifikasi_teknis" text [default: NULL]
  "perkiraan_harga" decimal(15,2) [default: NULL]
  "jumlah_diminta" int(11) [not null, default: 1]
  "satuan" varchar(50) [default: NULL]
  "urgensi" wishlist_aset_urgensi_enum [not null, default: 'sedang']
  "referensi_url" varchar(255) [default: NULL]
  "status_item" wishlist_aset_status_item_enum [not null, default: 'diajukan']
  "jumlah_disetujui" int(11) [default: NULL]
  "catatan_item" text [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Ref "absensi_jadwal_piket_foreign":"jadwal_piket"."id" < "absensi"."jadwal_piket" [delete: cascade]

Ref "absensi_periode_piket_id_foreign":"periode_piket"."id" < "absensi"."periode_piket_id" [delete: cascade]

Ref "absensi_aslab_pertemuan_id_foreign":"pertemuan_praktikum"."id" < "absensi_aslab"."pertemuan_id" [delete: cascade]

Ref "absensi_aslab_user_id_foreign":"users"."id" < "absensi_aslab"."user_id" [delete: cascade]

Ref "absensi_praktikan_pertemuan_id_foreign":"pertemuan_praktikum"."id" < "absensi_praktikan"."pertemuan_id" [delete: cascade]

Ref "absensi_praktikan_praktikan_id_foreign":"praktikan"."id" < "absensi_praktikan"."praktikan_id" [delete: cascade]

Ref "aslab_praktikum_praktikum_id_foreign":"praktikum"."id" < "aslab_praktikum"."praktikum_id" [delete: cascade]

Ref "aslab_praktikum_user_id_foreign":"users"."id" < "aslab_praktikum"."user_id" [delete: cascade]

Ref "detail_aset_aset_id_foreign":"kategori_aset"."id" < "detail_aset"."kategori_aset_id" [delete: cascade]

Ref "dokumentasi_kegiatan_kegiatan_id_foreign":"kegiatan"."id" < "dokumentasi_kegiatan"."kegiatan_id" [delete: cascade]

Ref "dokumentasi_kegiatan_uploaded_by_foreign":"users"."id" < "dokumentasi_kegiatan"."uploaded_by" [delete: set null]

Ref "ganti_jadwal_piket_approved_by_foreign":"users"."id" < "ganti_jadwal_piket"."approved_by" [delete: set null]

Ref "ganti_jadwal_piket_jadwal_piket_id_foreign":"jadwal_piket"."id" < "ganti_jadwal_piket"."jadwal_piket_id" [delete: cascade]

Ref "ganti_jadwal_piket_periode_piket_id_foreign":"periode_piket"."id" < "ganti_jadwal_piket"."periode_piket_id" [delete: cascade]

Ref "ganti_jadwal_piket_user_id_foreign":"users"."id" < "ganti_jadwal_piket"."user_id" [delete: cascade]

Ref "jadwal_piket_kepengurusan_lab_id_foreign":"kepengurusan_lab"."id" < "jadwal_piket"."kepengurusan_lab_id" [delete: cascade]

Ref "jadwal_piket_user_id_foreign":"users"."id" < "jadwal_piket"."user_id" [delete: cascade]

Ref "jadwal_praktikum_kelas_id_foreign":"kelas"."id" < "jadwal_praktikum"."kelas_id" [delete: cascade]

Ref "jawaban_kuesioner_pertanyaan_id_foreign":"pertanyaan_kuesioner"."id" < "jawaban_kuesioner"."pertanyaan_id" [delete: cascade]

Ref "jawaban_kuesioner_respon_id_foreign":"respon_kuesioner"."id" < "jawaban_kuesioner"."respon_id" [delete: cascade]

Ref "aset_laboratorium_id_foreign":"laboratorium"."id" < "kategori_aset"."laboratorium_id" [delete: cascade]

Ref "kegiatan_approved_by_foreign":"users"."id" < "kegiatan"."approved_by"

Ref "kegiatan_proker_id_foreign":"proker"."id" < "kegiatan"."proker_id" [delete: cascade]

Ref "kegiatan_peserta_kegiatan_id_foreign":"kegiatan"."id" < "kegiatan_peserta"."kegiatan_id" [delete: cascade]

Ref "kegiatan_peserta_user_id_foreign":"users"."id" < "kegiatan_peserta"."user_id" [delete: cascade]

Ref "kelas_praktikum_id_foreign":"praktikum"."id" < "kelas"."praktikum_id" [delete: cascade]

Ref "kepengurusan_lab_laboratorium_id_foreign":"laboratorium"."id" < "kepengurusan_lab"."laboratorium_id" [delete: cascade]

Ref "kepengurusan_lab_tahun_kepengurusan_id_foreign":"tahun_kepengurusan"."id" < "kepengurusan_lab"."tahun_kepengurusan_id" [delete: cascade]

Ref "kepengurusan_user_kepengurusan_lab_id_foreign":"kepengurusan_lab"."id" < "kepengurusan_user"."kepengurusan_lab_id" [delete: cascade]

Ref "kepengurusan_user_struktur_id_foreign":"struktur"."id" < "kepengurusan_user"."struktur_id" [delete: cascade]

Ref "kepengurusan_user_user_id_foreign":"users"."id" < "kepengurusan_user"."user_id" [delete: cascade]

Ref "komponen_rubrik_tugas_praktikum_id_foreign":"tugas_praktikum"."id" < "komponen_rubrik"."tugas_praktikum_id" [delete: cascade]

Ref "kuesioner_dibuat_oleh_foreign":"users"."id" < "kuesioner"."dibuat_oleh" [delete: cascade]

Ref "laporan_kegiatan_kegiatan_id_foreign":"kegiatan"."id" < "laporan_kegiatan"."kegiatan_id" [delete: cascade]

Ref "laporan_keuangan_kepengurusan_lab_id_foreign":"kepengurusan_lab"."id" < "laporan_keuangan"."kepengurusan_lab_id" [delete: cascade]

Ref "model_has_permissions_permission_id_foreign":"permissions"."id" < "model_has_permissions"."permission_id" [delete: cascade]

Ref "model_has_roles_role_id_foreign":"roles"."id" < "model_has_roles"."role_id" [delete: cascade]

Ref "modul_praktikum_pertemuan_id_foreign":"pertemuan_praktikum"."id" < "modul_praktikum"."pertemuan_id" [delete: cascade]

Ref "modul_praktikum_praktikum_id_foreign":"praktikum"."id" < "modul_praktikum"."praktikum_id" [delete: cascade]

Ref "nilai_rubrik_dinilai_oleh_foreign":"users"."id" < "nilai_rubrik"."dinilai_oleh" [delete: cascade]

Ref "nilai_rubrik_komponen_rubrik_id_foreign":"komponen_rubrik"."id" < "nilai_rubrik"."komponen_rubrik_id" [delete: cascade]

Ref "nilai_rubrik_pengumpulan_tugas_id_foreign":"pengumpulan_tugas"."id" < "nilai_rubrik"."pengumpulan_tugas_id" [delete: cascade]

Ref "nilai_tambahan_diberikan_oleh_foreign":"users"."id" < "nilai_tambahan"."diberikan_oleh" [delete: cascade]

Ref "nilai_tambahan_pengumpulan_tugas_id_foreign":"pengumpulan_tugas"."id" < "nilai_tambahan"."pengumpulan_tugas_id" [delete: cascade]

Ref "nominal_kas_kepengurusan_lab_id_foreign":"kepengurusan_lab"."id" < "nominal_kas"."kepengurusan_lab_id" [delete: cascade]

Ref "pengumpulan_tugas_praktikan_id_foreign":"praktikan"."id" < "pengumpulan_tugas"."praktikan_id" [delete: cascade]

Ref "pengumpulan_tugas_tugas_praktikum_id_foreign":"tugas_praktikum"."id" < "pengumpulan_tugas"."tugas_praktikum_id" [delete: cascade]

Ref "periode_piket_kepengurusan_lab_id_foreign":"kepengurusan_lab"."id" < "periode_piket"."kepengurusan_lab_id" [delete: cascade]

Ref "permohonan_aset_approved_by_foreign":"users"."id" < "permohonan_aset"."approved_by"

Ref "permohonan_aset_laboratorium_id_foreign":"laboratorium"."id" < "permohonan_aset"."laboratorium_id"

Ref "permohonan_aset_user_pemohon_id_foreign":"users"."id" < "permohonan_aset"."user_pemohon_id"

Ref "pertanyaan_kuesioner_kuesioner_id_foreign":"kuesioner"."id" < "pertanyaan_kuesioner"."kuesioner_id" [delete: cascade]

Ref "pertemuan_praktikum_kelas_id_foreign":"kelas"."id" < "pertemuan_praktikum"."kelas_id" [delete: cascade]

Ref "pertemuan_praktikum_praktikum_id_foreign":"praktikum"."id" < "pertemuan_praktikum"."praktikum_id" [delete: cascade]

Ref "praktikan_user_id_foreign":"users"."id" < "praktikan"."user_id" [delete: set null]

Ref "praktikan_praktikum_kelas_id_foreign":"kelas"."id" < "praktikan_praktikum"."kelas_id" [delete: cascade]

Ref "praktikan_praktikum_praktikan_id_foreign":"praktikan"."id" < "praktikan_praktikum"."praktikan_id" [delete: cascade]

Ref "praktikan_praktikum_praktikum_id_foreign":"praktikum"."id" < "praktikan_praktikum"."praktikum_id" [delete: cascade]

Ref "praktikum_kepengurusan_lab_id_foreign":"kepengurusan_lab"."id" < "praktikum"."kepengurusan_lab_id" [delete: cascade]

Ref "profile_user_id_foreign":"users"."id" < "profile"."user_id" [delete: cascade]

Ref "proker_kepengurusan_lab_id_foreign":"kepengurusan_lab"."id" < "proker"."kepengurusan_lab_id" [delete: cascade]

Ref "proker_struktur_id_foreign":"struktur"."id" < "proker"."struktur_id" [delete: cascade]

Ref "proker_dokumentasi_proker_id_foreign":"proker"."id" < "proker_dokumentasi"."proker_id" [delete: cascade]

Ref "proker_dokumentasi_uploaded_by_foreign":"users"."id" < "proker_dokumentasi"."uploaded_by" [delete: set null]

Ref "proker_parameter_proker_id_foreign":"proker"."id" < "proker_parameter"."proker_id" [delete: cascade]

Ref "proker_pj_proker_id_foreign":"proker"."id" < "proker_pj"."proker_id" [delete: cascade]

Ref "proker_pj_user_id_foreign":"users"."id" < "proker_pj"."user_id" [delete: cascade]

Ref "respon_kuesioner_kuesioner_id_foreign":"kuesioner"."id" < "respon_kuesioner"."kuesioner_id" [delete: cascade]

Ref "respon_kuesioner_user_id_foreign":"users"."id" < "respon_kuesioner"."user_id" [delete: cascade]

Ref "riwayat_keuangan_kepengurusan_lab_id_foreign":"kepengurusan_lab"."id" < "riwayat_keuangan"."kepengurusan_lab_id" [delete: cascade]

Ref "riwayat_keuangan_user_id_foreign":"users"."id" < "riwayat_keuangan"."user_id" [delete: set null]

Ref "role_has_permissions_permission_id_foreign":"permissions"."id" < "role_has_permissions"."permission_id" [delete: cascade]

Ref "role_has_permissions_role_id_foreign":"roles"."id" < "role_has_permissions"."role_id" [delete: cascade]

Ref "sertifikat_kepengurusan_lab_id_foreign":"kepengurusan_lab"."id" < "sertifikat"."kepengurusan_lab_id"

Ref "sertifikat_praktikum_id_foreign":"praktikum"."id" < "sertifikat"."praktikum_id"

Ref "sertifikat_user_id_foreign":"users"."id" < "sertifikat"."user_id"

Ref "struktur_default_role_id_foreign":"roles"."id" < "struktur"."default_role_id"

Ref "struktur_parent_id_foreign":"struktur"."id" < "struktur"."parent_id" [delete: set null]

Ref "surat_penerima_foreign":"users"."id" < "surat"."penerima" [delete: cascade]

Ref "surat_pengirim_foreign":"users"."id" < "surat"."pengirim" [delete: cascade]

Ref "target_kuesioner_kuesioner_id_foreign":"kuesioner"."id" < "target_kuesioner"."kuesioner_id" [delete: cascade]

Ref "tugas_praktikum_kelas_id_foreign":"kelas"."id" < "tugas_praktikum"."kelas_id" [delete: cascade]

Ref "tugas_praktikum_pertemuan_id_foreign":"pertemuan_praktikum"."id" < "tugas_praktikum"."pertemuan_id" [delete: cascade]

Ref "tugas_praktikum_praktikum_id_foreign":"praktikum"."id" < "tugas_praktikum"."praktikum_id" [delete: cascade]

Ref "users_access_lab_id_foreign":"laboratorium"."id" < "users"."access_lab_id" [delete: set null]

Ref "wishlist_aset_permohonan_aset_id_foreign":"permohonan_aset"."id" < "wishlist_aset"."permohonan_aset_id" [delete: cascade]

