import Button from '@/Components/Button';
import { DataGrid } from '@/Components/DataTable';
import FormField from '@/Components/FormField';
import PageHeader from '@/Components/PageHeader';
import PageSection from '@/Components/PageSection';
import DashboardLayout from '@/Layouts/DashboardLayout';
import { Head, useForm } from '@inertiajs/react';
import { ArrowLeft } from 'lucide-react';
import { toast } from 'sonner';

const VARIABLES = [
    { token: '{nomor}', desc: 'Nomor urut (misal: 1, 2, 3)' }, { token: '{inisial_lab}', desc: 'Inisial laboratorium' }, { token: '{bulan_romawi}', desc: 'Bulan dalam angka romawi' }, { token: '{tahun}', desc: 'Tahun 4 digit' }, { token: '{bulan}', desc: 'Bulan 2 digit' },
];

export default function Konfigurasi({ kepengurusanLab, konfigurasi }) {
    const form = useForm({ kepengurusan_lab_id: konfigurasi?.kepengurusan_lab_id || kepengurusanLab?.id || '', inisial_lab: konfigurasi?.inisial_lab || 'LAB', format_nomor: konfigurasi?.format_nomor || '{nomor}/LAB.{inisial_lab}/{bulan_romawi}/{tahun}', reset_tiap_tahun: konfigurasi?.reset_tiap_tahun ?? true });
    const preview = () => { const now = new Date(); const roman = ['I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII']; return form.data.format_nomor.replace('{nomor}', '1').replace('{inisial_lab}', form.data.inisial_lab).replace('{bulan_romawi}', roman[now.getMonth()]).replace('{tahun}', String(now.getFullYear())).replace('{bulan}', String(now.getMonth() + 1).padStart(2, '0')); };
    const submit = (event) => { event.preventDefault(); form.post(route('surat-menyurat.konfigurasi.upsert'), { onSuccess: () => toast.success('Konfigurasi berhasil disimpan'), onError: (errors) => toast.error(Object.values(errors)[0] || 'Gagal menyimpan konfigurasi') }); };
    return <DashboardLayout><Head title="Konfigurasi Surat" /><div className="max-w-3xl"><PageHeader title="Konfigurasi Nomor Surat" description={kepengurusanLab ? `${kepengurusanLab.laboratorium?.nama} · ${kepengurusanLab.tahunKepengurusan?.tahun}` : 'Atur format penomoran surat keluar.'} actions={<Button variant="ghost" onClick={() => history.back()}><ArrowLeft className="h-4 w-4" />Kembali</Button>} /><PageSection><form onSubmit={submit} className="space-y-5"><FormField label="Inisial laboratorium" error={form.errors.inisial_lab} required><input className="input input-bordered min-h-11 w-full uppercase" maxLength={20} value={form.data.inisial_lab} onChange={(e) => form.setData('inisial_lab', e.target.value.toUpperCase())} required /></FormField><FormField label="Format nomor surat keluar" error={form.errors.format_nomor} required><input className="input input-bordered min-h-11 w-full font-mono" value={form.data.format_nomor} onChange={(e) => form.setData('format_nomor', e.target.value)} required /></FormField><div className="flex flex-wrap gap-2" aria-label="Token format">{VARIABLES.map((item) => <Button key={item.token} size="sm" variant="ghost" onClick={() => form.setData('format_nomor', form.data.format_nomor + item.token)} title={item.desc}>{item.token}</Button>)}</div><div className="alert alert-info"><span>Pratinjau: <strong className="font-mono">{preview()}</strong></span></div><DataGrid rows={VARIABLES} columns={[{ key: 'token', header: 'Token' }, { key: 'desc', header: 'Keterangan' }]} searchPlaceholder="Cari token..." defaultPerPage={10} emptyMessage="Token tidak tersedia." /><FormField><label className="flex min-h-11 cursor-pointer items-center gap-3"><input type="checkbox" className="toggle toggle-primary" checked={form.data.reset_tiap_tahun} onChange={(e) => form.setData('reset_tiap_tahun', e.target.checked)} /><span>Reset nomor urut setiap tahun kepengurusan</span></label></FormField><div className="flex flex-col-reverse gap-2 border-t border-base-300 pt-4 sm:flex-row sm:justify-end"><Button variant="ghost" onClick={() => history.back()}>Batal</Button><Button type="submit" loading={form.processing}>Simpan konfigurasi</Button></div></form></PageSection></div></DashboardLayout>;
}
