@startuml ACT_01_MENGELOLA_RIWAYAT_KEUANGAN
!theme plain
!pragma useVerticalIf on
scale max 1600 width
skinparam wrapWidth 200
skinparam defaultFontSize 12
skinparam TitleFontSize 14
skinparam swimlaneWidth 260
skinparam ActivityStartColor black
skinparam ActivityEndColor black
skinparam ConditionEndStyle hline
title ACT-01 - Mengelola Riwayat Keuangan

|Admin|
|System|

|Admin|
start
:Buka menu Riwayat Keuangan;
|System|
:Query & Tampilkan daftar transaksi;
|Admin|
:Lihat daftar transaksi & saldo;

if (Aksi?) then (Tambah)
  :Tekan tombol Tambah;
  |System|
  :Tampilkan Form Transaksi;
  |Admin|
  :Isi form transaksi;

elseif (Aksi?) then (Edit)
  :Tekan tombol Edit,\npilih transaksi yang diubah;
  |System|
  :Tampilkan Form Edit Transaksi;
  |Admin|
  :Ubah data transaksi;

elseif (Aksi?) then (Hapus)
  :Klik Hapus, konfirmasi;
  |System|
  :Tampilkan Konfirmasi Hapus;
  |Admin|
  :Konfirmasi penghapusan;

else (Export PDF)
  :Klik Export PDF\n;
  |System|
  :Ambil data riwayat sesuai filter;
  :Buat file PDF;
  :Mulai unduhan file PDF;
endif

|System|
:Melakukan Validasi;
if (Valid?) then (tidak)
  :Tampilkan Pesan Error;
  |Admin|
  :Perbaiki data;
  |System|
else (ya)
  :Tampilkan Pesan Sukses;
endif

stop
@enduml
