@startuml ACT_02_MENGELOLA_NOMINAL_KAS
!theme plain
!pragma useVerticalIf on
scale max 1600 width
skinparam wrapWidth 200
skinparam defaultFontSize 12
skinparam TitleFontSize 14
skinparam swimlaneWidth 260
skinparam ActivityStartColor black
skinparam ActivityEndColor black
skinparam ConditionEndStyle hline
title ACT-02 - Mengelola Nominal Kas

|SuperAdmin / Admin|
|System|

|SuperAdmin / Admin|
start
:Buka menu Pengaturan Kas\n/ Nominal Kas;
|System|
:Query & Tampilkan nominal kas;
|SuperAdmin / Admin|
:Lihat nominal kas;

if (Aksi?) then (Tambah)
  :Tekan tombol Tambah;
  |System|
  :Tampilkan Form Nominal Kas;
  |SuperAdmin / Admin|
  :Isi form;

elseif (Aksi?) then (Edit)
  :Tekan tombol Edit,\npilih nominal kas yang diubah;
  |System|
  :Tampilkan Form Edit Nominal;
  |SuperAdmin / Admin|
  :Ubah nominal kas;

elseif (Aksi?) then (Toggle)
  :Klik toggle status aktif;
  |System|
  :Perbarui data;

else (Hapus)
  :Klik Hapus, konfirmasi;
  |System|
  :Tampilkan Konfirmasi Hapus;
  |SuperAdmin / Admin|
  :Konfirmasi penghapusan;
endif

|System|
:Melakukan Validasi;
if (Valid?) then (tidak)
  :Tampilkan Pesan Error;
  |SuperAdmin / Admin|
  :Perbaiki data;
  |System|
else (ya)
  :Tampilkan Pesan Sukses;
endif

stop
@enduml
