@startuml ACT_03_MELIHAT_CATATAN_KAS
!theme plain
!pragma useVerticalIf on
scale max 1600 width
skinparam wrapWidth 200

skinparam defaultFontSize 12
skinparam TitleFontSize 14
skinparam swimlaneWidth 220
skinparam ActivityStartColor black
skinparam ActivityEndColor black
skinparam ConditionEndStyle hline
title ACT-03 - Melihat Catatan Kas / Asisten / Dosen / Kadep

|Superadmin / Admin / Asisten / Dosen / Kadep|
|System|

|Superadmin / Admin / Asisten / Dosen / Kadep|
start
:Buka menu Catatan Kas;

|System|
:Cek autentikasi & role;
:Ambil data kepengurusan lab aktif;
:Ambil data matriks pembayaran kas;
:Hitung status lunas / belum\nper anggota per bulan;
:Tampilkan matriks catatan kas;

|Superadmin / Admin / Asisten / Dosen / Kadep|
:Lihat matriks pembayaran kas\n(siapa sudah bayar, siapa belum);
:Filter bulan / anggota ;

|System|
:Perbarui tampilan sesuai filter;
:Perbarui tampilan;

|Superadmin / Admin / Asisten / Dosen / Kadep|
:Lihat hasil filter;

stop
@enduml
