@startuml ACT_07_KONFIRMASI_PASSWORD
!theme plain
!pragma useVerticalIf on
scale max 1400 width
skinparam wrapWidth 180
skinparam defaultFontSize 12\nskinparam TitleFontSize 14
skinparam swimlaneWidth 200
skinparam ActivityStartColor black
skinparam ActivityEndColor black
skinparam ConditionEndStyle hline

title ACT-07 - Konfirmasi Password

|Pengguna|
|System|

|Pengguna|
start
:Akses halaman/aksi sensitif;

repeat
  :Isi form;
  :Klik Konfirmasi;
  |System|
  :Validasi password;
  |Pengguna|
repeat while (Password benar?) is (tidak) not (ya)

|System|
:Simpan status konfirmasi password;
:Redirect ke halaman tujuan;

|Pengguna|
:Lanjut akses fitur sensitif;

stop
@enduml
