@startuml ACT_03_LUPA_RESET_PASSWORD
!theme plain
!pragma useVerticalIf on
scale max 1400 width
skinparam wrapWidth 180
skinparam defaultFontSize 12\nskinparam TitleFontSize 14
skinparam swimlaneWidth 200
skinparam ActivityStartColor black
skinparam ActivityEndColor black
skinparam ConditionEndStyle hline

title ACT-03 - Lupa & Reset Password

|Publik|
|System|

|Publik|
start
:Buka halaman lupa password;

repeat
  :Isi email;
  :Kirim permintaan reset;
  |System|
  :Validasi email;
  |Publik|
repeat while (Email valid?) is (tidak) not (ya)

|System|
:Kirim link reset password;

|Publik|
:Buka link reset dari email;

repeat
  :Isi form reset password;
  :Submit reset password;
  |System|
  :Validasi token dan data reset;
  |Publik|
repeat while (Data reset valid?) is (tidak) not (ya)

|System|
:Update password user;
:Hapus token reset;
:Redirect ke login + pesan sukses;

|Publik|
:Login dengan password baru;

stop
@enduml
