@startuml ACT_01_LOGIN
!theme plain
!pragma useVerticalIf on
scale max 800 width
skinparam wrapWidth 140
skinparam defaultFontSize 12
skinparam TitleFontSize 14
skinparam swimlaneWidth 200
skinparam ActivityStartColor black
skinparam ActivityEndColor black
skinparam ConditionEndStyle hline

title ACT-01 - Login

|Publik| 
|System|

|Publik|
start
:Buka halaman login;

repeat
  :Isi form login;
  :Klik Login;
  |System|
  :Validasi kredensial;
  |Publik|
repeat while (Login gagal?) is (ya) not (tidak)

|System|
:Buat sesi login;

if (Role = praktikan?) then (ya)
  :Redirect ke daftar tugas;
else (tidak)
  :Redirect ke dashboard;
endif

|Publik|
:Masuk ke halaman tujuan;
stop
@enduml
