@startuml ACT_14_MELIHAT_DAFTAR_PROKER
!theme plain
!pragma useVerticalIf on
scale max 1600 width
skinparam wrapWidth 200

skinparam defaultFontSize 12\nskinparam TitleFontSize 14
skinparam swimlaneWidth 220
skinparam ActivityStartColor black
skinparam ActivityEndColor black
skinparam ConditionEndStyle hline
title ACT-14 - Melihat Daftar Prokern / Kadep

|Dosen / Kadep|
|System|

|Dosen / Kadep|
start
:Buka menu Daftar Proker;

|System|
:Cek autentikasi & role;
:Tampilkan daftar proker;

|Dosen / Kadep|
:Lihat daftar proker;
:Pilih filter (status, lab, tahun)\n;

|System|
:Perbarui tampilan sesuai filter;
:Tampilkan hasil filter;

|Dosen / Kadep|
:Klik proker ? lihat detail ;

|System|
:Ambil data detail proker;
:Tampilkan halaman detail proker;

|Dosen / Kadep|
:Lihat detail proker;

stop
@enduml
