@startuml ACT_13_MENGELOLA_ANGGOTA
!theme plain
!pragma useVerticalIf on
scale max 1600 width
skinparam wrapWidth 200
skinparam defaultFontSize 12
skinparam swimlaneWidth 260
skinparam ActivityStartColor black
skinparam ActivityEndColor black
title ACT-13 - Mengelola Anggota\nAktor: Admin

|Admin|
|System|

|Admin|
start
:Buka menu Anggota Kepengurusan;
|System|
:Query & Tampilkan daftar anggota;
|Admin|
:Lihat daftar anggota;

if (Aksi?) then (Tambah)
  :Tekan tombol Tambah;
  |System|
  :Tampilkan Form Anggota;
  |Admin|
  :Pilih user + isi jabatan, divisi;

elseif (Aksi?) then (Edit)
  :Tekan tombol Edit,\npilih anggota yang diubah;
  |System|
  :Tampilkan Form Edit Anggota;
  |Admin|
  :Ubah jabatan / divisi;

else (Hapus)
  :Pilih anggota, klik Hapus;
  |System|
  :Tampilkan Konfirmasi Hapus;
  |Admin|
  :Konfirmasi penghapusan;
endif

|System|
:Melakukan Validasi;
if (Valid?) then (tidak)
  :Tampilkan Pesan Error;
  |Admin|
  :Perbaiki data;
  |System|
else (ya)
  :Tampilkan Pesan Sukses;
  |Admin|
endif

stop
@enduml
