@startuml ACT_06_MENGELOLA_KEGIATAN
!theme plain
!pragma useVerticalIf on
scale max 1600 width
skinparam wrapWidth 200
skinparam defaultFontSize 12\nskinparam TitleFontSize 14
skinparam swimlaneWidth 260
skinparam ActivityStartColor black
skinparam ActivityEndColor black
skinparam ConditionEndStyle hline
title ACT-06 - Mengelola Kegiatan

|Admin|
|System|

|Admin|
start
:Buka menu Kegiatan;
|System|
:Query & Tampilkan daftar kegiatan;
|Admin|
:Lihat daftar kegiatan;

if (Aksi?) then (Tambah)
  :Tekan tombol Tambah;
  |System|
  :Tampilkan Form Kegiatan;
  |Admin|
  :Isi form kegiatan;

elseif (Aksi?) then (Edit)
  :Tekan tombol Edit,\npilih kegiatan yang diubah;
  |System|
  :Tampilkan Form Edit Kegiatan;
  |Admin|
  :Ubah data kegiatan;

elseif (Aksi?) then (Hapus)
  :Klik Hapus, konfirmasi;
  |System|
  :Tampilkan Konfirmasi Hapus;
  |Admin|
  :Konfirmasi penghapusan;

else (Ajukan)
  :Klik Ajukan;
  |System|
  :Perbarui data;
  :Kirim notifikasi ke Kadep/Dosen;
endif

|System|
:Melakukan Validasi;
if (Valid?) then (tidak)
  :Tampilkan Pesan Error;
  |Admin|
  :Perbaiki data;
  |System|
else (ya)
  :Tampilkan Pesan Sukses;
endif

stop
@enduml
