@startuml ACT_15_MELIHAT_DAFTAR_KEGIATAN
!theme plain
!pragma useVerticalIf on
scale max 1600 width
skinparam wrapWidth 200

skinparam defaultFontSize 12
skinparam TitleFontSize 14
skinparam swimlaneWidth 220
skinparam ActivityStartColor black
skinparam ActivityEndColor black
skinparam ConditionEndStyle hline
title ACT-15 - Melihat Daftar Kegiatann / Kadep

|Dosen / Kadep|
|System|

|Dosen / Kadep|
start
:Buka menu Daftar Kegiatan;

|System|
:Cek autentikasi & role;
:Tampilkan daftar kegiatan;

|Dosen / Kadep|
:Lihat daftar kegiatan;
:Pilih filter ;

|System|
:Perbarui tampilan sesuai filter;
:Tampilkan hasil filter;

|Dosen / Kadep|
:Klik kegiatan ? lihat detail ;

|System|
:Ambil data detail kegiatan;
:Tampilkan halaman detail kegiatan;

|Dosen / Kadep|
:Lihat detail kegiatan;

stop
@enduml
