@startuml ACT_13_MENGELOLA_ANGGOTA
!theme plain
!pragma useVerticalIf on
scale max 1600 width
skinparam wrapWidth 200
skinparam defaultFontSize 12
skinparam TitleFontSize 14
skinparam swimlaneWidth 260
skinparam ActivityStartColor black
skinparam ActivityEndColor black
skinparam ConditionEndStyle hline
title ACT-13 - Mengelola Anggota

|SuperAdmin / Admin|
|System|

|SuperAdmin / Admin|
start
:Buka menu Anggota Kepengurusan;
|System|
:Query & Tampilkan daftar anggota;
|SuperAdmin / Admin|
:Lihat daftar anggota;

if (Aksi?) then (Tambah)
  :Tekan tombol Tambah;
  |System|
  :Tampilkan Form Anggota;
  |SuperAdmin / Admin|
  :Pilih user + isi jabatan, divisi;

elseif (Aksi?) then (Edit)
  :Tekan tombol Edit,\npilih anggota yang diubah;
  |System|
  :Tampilkan Form Edit Anggota;
  |SuperAdmin / Admin|
  :Ubah jabatan / divisi;

else (Hapus)
  :Pilih anggota, klik Hapus;
  |System|
  :Tampilkan Konfirmasi Hapus;
  |SuperAdmin / Admin|
  :Konfirmasi penghapusan;
endif

|System|
:Melakukan Validasi;
if (Valid?) then (tidak)
  :Tampilkan Pesan Error;
  |SuperAdmin / Admin|
  :Perbaiki data;
  |System|
else (ya)
  :Tampilkan Pesan Sukses;
endif

stop
@enduml
