@startuml ACT_08_APPROVAL_PERMOHONAN_KADEP
!theme plain
!pragma useVerticalIf on
scale max 1200 width
skinparam wrapWidth 160
skinparam defaultFontSize 12\nskinparam TitleFontSize 14
skinparam swimlaneWidth 180
skinparam ActivityStartColor black
skinparam ActivityEndColor black
skinparam ConditionEndStyle hline
title ACT-08 - Menyetujui / Menolak Permohonan Pengadaannu Permohonan Pengadaan;

|System|
:Tampilkan daftar permohonan\nstatus "direview_kalab";

|Kadep|
:Pilih permohonan;
:Ambil keputusan final;

if (Keputusan final?) then (Setuju)
  |Kadep|
  :Klik Setuju;

  |System|
  :Perbarui data;
  :Kirim pesan permohonan disetujui;

  |Kadep|
  :Permohonan ditandai disetujui;

else (Tolak)
  repeat
    |Kadep|
    :Klik Tolak;
    :Isi alasan penolakan;
    |System|
    :Validasi form;
    |Kadep|
  repeat while (Form valid?) is (tidak) not (ya)

  |System|
  :Perbarui data;
  :Kirim pesan permohonan ditolak;

  |Kadep|
  :Permohonan ditandai ditolak;

endif

stop
@enduml
