@startuml ACT_02_MENGISI_KUESIONER
!theme plain
!pragma useVerticalIf on
scale max 800 width
skinparam wrapWidth 120
skinparam defaultFontSize 12\nskinparam TitleFontSize 14
skinparam swimlaneWidth 170
skinparam ActivityStartColor black
skinparam ActivityEndColor black
skinparam ConditionEndStyle hline
title ACT-02 - Mengisi Kuesioner / Praktikan

|Asisten / Praktikan|
|System|

|Asisten / Praktikan|
start
:Buka menu Kuesioner;
:Pilih kuesioner aktif;

repeat
  :Isi form;
  :Klik Submit;
  |System|
  :Validasi form;
  |Asisten / Praktikan|
repeat while (Valid?) is (tidak) not (ya)

|System|
:Simpan jawaban;
:Tampilkan pesan sukses;

|Asisten / Praktikan|
:Kuesioner berhasil terkirim;

stop
@enduml
