@startuml ACT_03_MELIHAT_HASIL_KUESIONER
!theme plain
!pragma useVerticalIf on
scale max 900 width
skinparam wrapWidth 140
skinparam defaultFontSize 12
skinparam TitleFontSize 14
skinparam swimlaneWidth 190
skinparam ActivityStartColor black
skinparam ActivityEndColor black
skinparam ConditionEndStyle hline
title ACT-03 - Melihat Hasil Kuesioner / Kadep

|Superadmin / Admin / Kadep|
|System|

|Superadmin / Admin / Kadep|
start
:Buka menu Hasil Kuesioner;

|System|
:Tampilkan daftar kuesioner;

|Superadmin / Admin / Kadep|
:Pilih kuesioner;

|System|
:Tampilkan rekap hasil;

|Superadmin / Admin / Kadep|
:Lihat hasil kuesioner;

stop
@enduml
