@startuml ACT_17_MELIHAT_REKAP_PRAKTIKUM
!theme plain
!pragma useVerticalIf on
scale max 1600 width
skinparam wrapWidth 200

skinparam defaultFontSize 12
skinparam swimlaneWidth 220
skinparam ActivityStartColor black
skinparam ActivityEndColor black
title ACT-17 - Melihat Rekap Nilai & Absensi Praktikum\nAktor: Dosen / Kadep

|Dosen / Kadep|
|System|

|Dosen / Kadep|
start
:Buka menu Rekap Praktikum;

|System|
:Cek autentikasi & role;
:Tampilkan daftar praktikum;

|Dosen / Kadep|
:Pilih praktikum;

|System|
:Ambil data rekap per praktikan:;
:Tampilkan tabel rekap\nnilai & absensi;

|Dosen / Kadep|
:Lihat rekap;
:Filter pertemuan / tugas\n(opsional);

|System|
:Perbarui tampilan sesuai filter;
:Perbarui tampilan;

|Dosen / Kadep|
:Lihat detail rekap;

stop
@enduml
