@startuml ACT_01_MENGELOLA_PRAKTIKUM
!theme plain
!pragma useVerticalIf on
scale max 1600 width
skinparam wrapWidth 200
skinparam defaultFontSize 12
skinparam TitleFontSize 14
skinparam swimlaneWidth 260
skinparam ActivityStartColor black
skinparam ActivityEndColor black
skinparam ConditionEndStyle hline
title ACT-01 - Mengelola Praktikum

|SuperAdmin / Admin|
|System|

|SuperAdmin / Admin|
start
:Buka menu Praktikum;
|System|
:Query & Tampilkan daftar praktikum;
|SuperAdmin / Admin|
:Lihat daftar praktikum;

if (Aksi?) then (Tambah)
  :Tekan tombol Tambah;
  |System|
  :Tampilkan Form Tambah Praktikum;
  |SuperAdmin / Admin|
  :Isi form praktikum;

elseif (Aksi?) then (Edit)
  :Tekan tombol Edit,\npilih data yang ingin diubah;
  |System|
  :Tampilkan Form Edit Praktikum;
  |SuperAdmin / Admin|
  :Ubah data praktikum;

else (Hapus)
  :Tekan tombol Hapus,\npilih data yang ingin dihapus;
  |System|
  :Tampilkan Konfirmasi Hapus;
  |SuperAdmin / Admin|
  :Konfirmasi penghapusan;
endif

|System|
:Melakukan Validasi;
if (Valid?) then (tidak)
  :Tampilkan Pesan Error;
  |SuperAdmin / Admin|
  :Perbaiki data;
  |System|
else (ya)
  :Tampilkan Pesan Sukses;
endif

stop
@enduml
