@startuml ACT_08_MENGELOLA_TUGAS
!theme plain
!pragma useVerticalIf on
scale max 1600 width
skinparam wrapWidth 200
skinparam defaultFontSize 12\nskinparam TitleFontSize 14
skinparam swimlaneWidth 260
skinparam ActivityStartColor black
skinparam ActivityEndColor black
skinparam ConditionEndStyle hline
title ACT-08 - Mengelola Tugas Praktikum / Asisten

|Admin / Asisten|
|System|

|Admin / Asisten|
start
:Buka detail praktikum, tab Tugas;
|System|
:Query & Tampilkan daftar tugas;
|Admin / Asisten|
:Lihat daftar tugas;

if (Aksi?) then (Tambah)
  :Tekan tombol Tambah;
  |System|
  :Tampilkan Form Tambah Tugas;
  |Admin / Asisten|
  :Isi form tugas;

elseif (Aksi?) then (Edit)
  :Tekan tombol Edit,\npilih tugas yang diubah;
  |System|
  :Tampilkan Form Edit Tugas;
  |Admin / Asisten|
  :Ubah data tugas;

elseif (Aksi?) then (Hapus)
  :Tekan tombol Hapus,\npilih tugas yang dihapus;
  |System|
  :Tampilkan Konfirmasi Hapus;
  |Admin / Asisten|
  :Konfirmasi penghapusan;

else (Toggle Buka/Tutup)
  :Toggle status tugas\n(buka / tutup pengumpulan);
  |System|
  :Perbarui data;
endif

|System|
:Melakukan Validasi;
if (Valid?) then (tidak)
  :Tampilkan Pesan Error;
  |Admin / Asisten|
  :Perbaiki data;
  |System|
else (ya)
  :Tampilkan Pesan Sukses;
endif

stop
@enduml
