@startuml ACT_10_MENGELOLA_PENILAIAN
!theme plain
!pragma useVerticalIf on
scale max 1600 width
skinparam wrapWidth 200
skinparam defaultFontSize 12\nskinparam TitleFontSize 14
skinparam swimlaneWidth 260
skinparam ActivityStartColor black
skinparam ActivityEndColor black
skinparam ConditionEndStyle hline
title ACT-10 - Mengelola Penilaian Tugas / Asisten

|Admin / Asisten|
|System|

|Admin / Asisten|
start
:Buka detail tugas, tab Penilaian\n/ Pengumpulan;
|System|
:Query & Tampilkan daftar pengumpulan;
|Admin / Asisten|
:Lihat daftar pengumpulan;

if (Aksi?) then (Beri Nilai)
  :Pilih pengumpulan;
  |System|
  :Tampilkan Form Penilaian;
  |Admin / Asisten|
  :Isi nilai per komponen rubrik;

else (Export Nilai)
  :Klik Export Nilai;
  |System|
  :Ambil data semua nilai;
  :Buat file Excel;
  :Mulai unduhan file;
endif

|System|
:Melakukan Validasi;
if (Valid?) then (tidak)
  :Tampilkan Pesan Error;
  |Admin / Asisten|
  :Perbaiki data;
  |System|
else (ya)
  :Tampilkan Pesan Sukses;
endif

stop
@enduml
