@startuml ACT_15_RIWAYAT_PENGUMPULAN
!theme plain
!pragma useVerticalIf on
scale max 1600 width
skinparam wrapWidth 200

skinparam defaultFontSize 12
skinparam swimlaneWidth 220
skinparam ActivityStartColor black
skinparam ActivityEndColor black
title ACT-15 ? Melihat Riwayat Pengumpulan Tugas\nAktor: Praktikan

|Praktikan|
|System|

|Praktikan|
start
:Buka menu Riwayat Pengumpulan;

|System|
:Cek autentikasi & role;
:Ambil data pengumpulan tugas;
:Tampilkan daftar riwayat\n(judul tugas, tgl kumpul,\nnilai, status dinilai / belum);

|Praktikan|
:Lihat daftar riwayat pengumpulan;
:Klik pengumpulan ? lihat detail\n(opsional);

|System|
:Ambil data detail pengumpulan;
:Tampilkan halaman detail;

|Praktikan|
:Lihat detail pengumpulan & nilai;
:Unduh file tugas\nyang dikumpulkan (opsional);

|System|
:Mulai unduhan file;

|Praktikan|
:File berhasil diunduh;

stop
@enduml
